214 contributors
OpenSynergic/leconfe pull request #223
Opened 2024-03-27 02:51 UTC by faisalwahyudi10

**Perubahan Structure Table untuk Participant yang di ganti menjadi Contributor :**
![LeConfe - Contributors v2 drawio](https://github.com/OpenSynergic/leconfe/assets/121210620/7d77144d-a202-4329-a662-5fbbc6160f36)

**Perubahan Pada Submission Wizzard :**
- Contributors :
   Pada Submission Step Assign Contributor terdapat perubahan dimana hanya dapat me-assign Author yang sebelumnya dapat me-assign Author dan Speaker
![image](https://github.com/OpenSynergic/leconfe/assets/121210620/3da8e993-d7b4-4599-80ac-9299746bd4c5)

- Presenter
   Terdapat Step Tambahan Pada submission yaitu Presenter untuk me-assign Presenter pada Submission.
![image](https://github.com/OpenSynergic/leconfe/assets/121210620/6bedaa75-a374-4feb-8a6a-768d23f0b433)

- Review
   Pada Submission Step Review terdapat component table tambahan untuk presenter agar dapat melihat list presenter yang diassign saat review 
![image](https://github.com/OpenSynergic/leconfe/assets/121210620/9a70664a-f67e-4174-8690-53cbe882676e)

**Tambahan Presenter Resource**
  Pada Presenter Resource ini akan dapat melakukan action decision untuk approve atau reject contributor presenter pada submission

- Table :
![image](https://github.com/OpenSynergic/leconfe/assets/121210620/3b7b2840-6dd4-4bc7-8120-7ff9eb695ef3)
![image](https://github.com/OpenSynergic/leconfe/assets/121210620/ca46a57d-f62f-441b-bfa2-e610c60b6c9c)

- Form Approve dan Reject
![image](https://github.com/OpenSynergic/leconfe/assets/121210620/883b5306-79f4-41a4-b9b0-359be52d568f)
![image](https://github.com/OpenSynergic/leconfe/assets/121210620/36e07af6-1cd5-464c-806e-50608adad79b)

2024-03-30 01:05 UTC, rahmanramsi requested changes
.

2024-04-20 08:46 UTC, faisalwahyudi10 commented
Berikut Setting Author Roles yang dipindah ke Workflow conference

![image](https://github.com/OpenSynergic/leconfe/assets/121210620/c97ad5c6-58cc-47e9-8287-7f6c05ac30cb)

2024-04-20 08:47 UTC, faisalwahyudi10 commented
Berikut file-file yg tidak tepakai yg ulun remove :
https://github.com/OpenSynergic/leconfe/pull/223/commits/cb333a29aa5e606225f3e00d56fc8bc2fb7af70c

2024-04-20 09:00 UTC, faisalwahyudi10 commented
Berikut perubahan structure table contributor dari conferences ke series

![LeConfe - Contributors v2 drawio (1)](https://github.com/OpenSynergic/leconfe/assets/121210620/b3d47291-981f-4031-a1ca-579cc96d488c)

2024-04-24 00:21 UTC, rahmanramsi requested changes
- Untuk kolom slug di `speaker_roles`, `committee_roles`, dan yang terkait bisa dihapus aja kalau tidak dipakai.

- Ini bisa dihapus Headingnya karna di Tab nya sudah jelas namanya
![CleanShot 2024-04-24 at 08 18 29](https://github.com/OpenSynergic/leconfe/assets/48276043/1638b38a-e038-44bb-9183-3a5a0e73d649)

2024-04-24 00:21 UTC, rahmanramsi commented on app/Models/CommitteeRole.php
> +    }
Slug ini gsan apa sal?

2024-04-24 00:21 UTC, rahmanramsi commented on app/Models/CommitteeRole.php
> +    }
Kda tepakai kyanya ini

2024-04-24 00:24 UTC, rahmanramsi commented
Tab General ini bisa diganti jadi Advanced, dan taruh dipaling terakhir.

![CleanShot 2024-04-24 at 08 22 24](https://github.com/OpenSynergic/leconfe/assets/48276043/9e02e4c2-b136-4ac1-a5a9-44959f477def)

Ketika mengakses workflow, rasanya aneh diawal ditampilkan author roles.

2024-04-24 00:32 UTC, faisalwahyudi10 commented on app/Models/CommitteeRole.php
> +    }
Ini ulun menuruti struktur table Participant Position sebelumnya yg memiliki slug bang

2024-04-24 00:37 UTC, rahmanramsi commented on app/Models/CommitteeRole.php
> +    }
Bisa dihapus misal tidak terpakai

2024-04-24 03:38 UTC, faisalwahyudi10 commented
- [ ] Remove Slug Pada Author, Committe dan Speaker Roles
- [ ] Tab General ini bisa diganti jadi Advanced, dan taruh dipaling terakhir.
![Screenshot 2024-04-24 094039](https://github.com/OpenSynergic/leconfe/assets/121210620/2d564b2e-9ea6-45ee-9df6-965c2c39e725)

2024-04-24 08:41 UTC, rahmanramsi approved these changes

2024-04-24 08:42 UTC, merged