Audience service
OpenSynergic/leconfe pull request #319
Opened 2024-07-27 08:59 UTC by SalimQS

2024-07-29 07:04 UTC, rahmanramsi requested changes

2024-07-29 07:04 UTC, rahmanramsi commented on app/Actions/RegistrationTypes/RegistrationTypeCreateAction.php
> +            $registration_type = RegistrationType::create($data);
Agar tetap konsisten, penamaan variable seharusnya menggunakan `camelCase`,

2024-07-29 07:04 UTC, rahmanramsi commented on app/Frontend/ScheduledConference/Pages/ParticipantRegister.php
> +    public function rules()
Tambahkan return type ke setiap fungsi untuk memastikan variable yg direturn sesuai dengan yang diinginkan

2024-07-29 07:04 UTC, rahmanramsi commented on app/Frontend/ScheduledConference/Pages/ParticipantRegister.php
> +    public function rules()
referensi https://www.php.net/manual/en/language.types.declarations.php

2024-07-29 07:04 UTC, rahmanramsi commented on app/Frontend/ScheduledConference/Pages/ParticipantRegisterStatus.php
> +            ->whereScheduledConferenceId(app()->getCurrentScheduledConferenceId())
Jangan menggunakan shortcut where seperti ini, gunakan `where` yang normal agar memudahkan pencarian

2024-07-29 07:04 UTC, rahmanramsi commented on database/migrations/2024_07_24_114021_create_payment_method.php
> +        Schema::create('manual_payment', function (Blueprint $table) {
Penamaan database harusnya terscope sesuai konteksnya, misal tentang payment brarti, semua tentang payment harus diawali dengan `payment_` dan ditambah hal yg diperlukan, disini seharusnya diubah menjadi `payment_manuals` jadi semisal ada tabel baru dengan konteks payment, table baru tersebut juga diawali dengan `payment_` +. nama yg diinginkan. Dan juga harus dalam bentuk jamak, karena isi table pasti lebih dari 1.

2024-07-29 07:04 UTC, rahmanramsi commented on database/migrations/2024_07_15_153736_create_registration.php
> +        Schema::dropIfExists('registration_options');
Table ini ga ada, bakalan error jika dilakukan rollback migration

2024-07-29 07:04 UTC, rahmanramsi commented on resources/views/frontend/scheduledConference/pages/participant-register-status.blade.php
> +                            ring-gray-500/10
Pembuatan conditional class tolong gunakan blade directive `@class`, referensi disini https://laravel.com/docs/11.x/blade#conditional-classes

2024-07-29 07:04 UTC, rahmanramsi commented on app/Models/PaymentManual.php
> +    protected $table = 'manual_payment';
ubah jadi `payment_manuals`

2024-07-29 07:04 UTC, rahmanramsi commented on app/Models/Registration.php
> +    }
Kalau kolom nya terpisah antara status `trash` dengan yang lain. Maka implementasinya harus dipisah juga agar tidak rancu dalam cara penggunaan.

2024-07-29 07:04 UTC, rahmanramsi commented on app/Models/Registration.php
> +    }
Penggunaan `status` juga seharusnya dalam bentuk constant, jangan raw text seperti `paid`, `unpaid`. Lihat implementasi dari model lain seperti `Submission`.

2024-07-29 07:04 UTC, rahmanramsi commented on app/Models/Registration.php
> +    public function registration_type(): BelongsTo
Nama method seharusnya juga dalam bentuk `camelCase`

2024-07-29 07:04 UTC, rahmanramsi commented on app/Models/RegistrationType.php
> +        HasFactory;
Tolong formatting nya disamakan dengan yang sudah ada agar kode konsisten secara keseluruhan

2024-07-29 07:04 UTC, rahmanramsi commented on app/Models/RegistrationType.php
> +    }
Seharusnya untuk keperluan formatting di tampilan jangan ditaro fungsinya di model.

2024-07-29 07:04 UTC, rahmanramsi commented on app/Models/RegistrationType.php
> +    }
Seharusnya untuk keperluan formatting di tampilan jangan ditaro fungsinya di model.

2024-07-29 07:04 UTC, rahmanramsi commented on app/Models/ScheduledConference.php
> +
`camelCase`

2024-07-29 07:04 UTC, rahmanramsi commented on app/Models/ScheduledConference.php
> +    }
ini konteks nya valid seperti apa ?

2024-07-29 07:04 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Livewire/Payment/ManualPaymentPage.php
> +        InteractsWithTable;
ini juga formatting nya tolong disesuaikan

2024-07-29 07:04 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Livewire/Payment/ManualPaymentPage.php
> +        foreach($currencies as $currency) $options[$currency->id] = '(' . Str::upper($currency->id) . ') ' . $currency->name;
penggunaan foreach seharusnya menggunakan bracket `{}` agar mudah dibaca dan konsistensi dalam kode

2024-07-29 07:04 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Livewire/Payment/ManualPaymentPage.php
> +                ->options((static::getCurrencyOptions()))
kalo fungsi `getCurrencyOptions` cuman dipakai sekali, seharusnya tidak perlu dibuat fungsi

2024-07-29 07:04 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Livewire/Registration/RegistrationTypePage.php
> +                                    }
Jangan gunakan if didalam if, susah dibaca

2024-07-29 07:04 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Pages/PaymentSettings.php
> +        }
Kayanya untuk konteks ini, registration setting dan payment setting bergantung 1 sama lain. Jadi bagusnya digabung kedalam konteks `RegistrationSetting` saja. tidak perlu ada permission `PaymentSetting`

2024-07-29 07:04 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Resources/RegistrantResource/Pages/EnrollUser.php
> +                ')),
Gunakan `heredoc` format untuk membuat html didalam php

2024-07-29 07:04 UTC, rahmanramsi commented on resources/views/frontend/scheduledConference/pages/participant-register.blade.php
> +                                        <tr class="{{ $is_invalid ? 'bg-red-100' : null }}">
gunakan `@class`

2024-07-29 07:04 UTC, rahmanramsi commented on resources/views/frontend/scheduledConference/pages/participant-register.blade.php
> +                                        @endphp
Sebisa mungkin jangan gunakan directive `@php`

2024-07-29 07:04 UTC, rahmanramsi commented on resources/views/panel/scheduledConference/livewire/registration/registration-policy.blade.php
Untuk blade ini bisa dihapus, yang mereferensikan ke blade ini bisa diganti ke `forms.form`

2024-07-29 07:04 UTC, rahmanramsi commented on resources/views/panel/scheduledConference/livewire/payment/manual.blade.php
Untuk blade ini bisa dihapus, yang mereferensikan ke blade ini bisa diganti ke `tables.table`

2024-07-29 07:04 UTC, rahmanramsi commented on resources/views/panel/scheduledConference/livewire/registration/registration-type.blade.php
Untuk blade ini bisa dihapus, yang mereferensikan ke blade ini bisa diganti ke `tables.table`

2024-07-31 06:41 UTC, rahmanramsi requested changes
Halaman payments dan payment-settings sebaiknya digabung saja, tidak usah menggunakan sub navigation dari filament

![CleanShot 2024-07-31 at 14 41 41](https://github.com/user-attachments/assets/97b9e88e-036a-4891-b531-7e36c8d692fb)

2024-07-31 06:41 UTC, rahmanramsi commented on app/Models/Enums/RegistrationPaymentType.php
Payment type jangan enum, soalnya dinamis bisa bertambah atau berkurang. Tidak pasti selalu sama

2024-07-31 06:41 UTC, rahmanramsi commented on app/Models/Enums/RegistrationStatus.php
class ini ubah jadi RegistrationPaymentStatus

2024-07-31 06:41 UTC, rahmanramsi commented on app/Models/Registration.php
TRASH sebaiknya menggunakan [soft delete](https://laravel.com/docs/11.x/eloquent#soft-deleting) bawaan dari laravel

2024-07-31 06:41 UTC, rahmanramsi commented on database/migrations/2024_07_15_153736_create_registration.php
> +            $table->boolean('trashed')->default(false);
menggunakan soft delete saja

2024-07-31 07:23 UTC, SalimQS commented on app/Models/Enums/RegistrationStatus.php
diganti menjadi RegistrationPaymentState, mengikuti penamaan column `state` pada table `registration_payments`.

2024-07-31 07:29 UTC, SalimQS commented on app/Panel/ScheduledConference/Resources/RegistrantResource.php
> +    public static function getSubNavigation(): array
jangan menggunakan subnavigation bawaan filament, gunakan tabs. ubah resource ini menjadi page apa bila diperlukan

2024-08-01 04:00 UTC, rahmanramsi requested changes
Inputan participant quota bisa minus. Seharusnya tidak bisa, dan juga harus divalidasi bahwa angka tidak boleh minus

![CleanShot 2024-08-01 at 11 42 58](https://github.com/user-attachments/assets/c03a4ab0-e633-4f37-91e3-3e6af036b874)

2024-08-01 04:00 UTC, rahmanramsi commented on app/Models/Registration.php
Sudah pakai softdelete tapi kenapa masih ada status trashed?

2024-08-01 04:00 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Livewire/Payment/PaymentManualPage.php
Ini livewire component, tapi kenapa ada nama `Page` nya ?

2024-08-01 04:00 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Livewire/Payment/PaymentSettingPage.php
Ini livewire component, tapi kenapa ada nama `Page` nya ?

2024-08-01 04:00 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Livewire/Registration/RegistrationPolicyPage.php
Ini livewire component, tapi kenapa ada nama `Page` nya ?

2024-08-01 04:00 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Livewire/Registration/RegistrationTypePage.php
Ini livewire component, tapi kenapa ada nama `Page` nya ?

2024-08-01 04:00 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Pages/Payments.php
> +    protected static ?string $navigationLabel = 'Payment';
Seharusnya Payments, karna konteksnya ini lebih dari 1 payment

2024-08-01 04:00 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Pages/Payments.php
> +    protected static ?string $title = 'Payment Method';
ini juga seharusnya `Payment Methods` karna konteksnya ini lebih dari 1 payment

2024-08-01 04:00 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Resources/RegistrantResource/Pages/ListRegistrants.php
> +    // protected static string $view = 'panel.scheduledConference.resources.registrant-resource.pages.list-registrant';
Kalau memang tidak dipakai lagi, jangan lupa dihapus filenya. Dan juga jangan di jadikan `comment`, harus di hapus dengan benar, Agar kode bersih dari hal-hal yang tidak ada hubungannya.

2024-08-01 04:00 UTC, rahmanramsi commented on resources/views/panel/scheduledConference/resources/registrant-resource/pages/list-registrant.blade.php
> +            {{-- <div class="grid grid-cols-12 gap-4"> --}}
code yg tidak terpakai bisa dihapus

2024-08-01 07:15 UTC, SalimQS commented on app/Models/Registration.php
maaf ka, setelah dicek lagi, memang salah. semua sudah diubah penggunaannya hanya menggunakan softdelete laravel.

2024-08-01 07:21 UTC, rahmanramsi requested changes

2024-08-01 07:21 UTC, rahmanramsi commented on resources/views/frontend/scheduledConference/pages/participant-register-status.blade.php
> +                                    @endif
ini seharusnya bisa disederhakan, yg berbeda cuman `md:col-span-6` dengan `md:col-span-3`

2024-08-01 07:21 UTC, rahmanramsi commented on resources/views/frontend/scheduledConference/pages/participant-register-status.blade.php
> +            @endempty
pakai `@if` saja jadi lebih mudah dibaca

2024-08-01 07:27 UTC, rahmanramsi approved these changes

2024-08-01 07:27 UTC, merged