Conference Agenda & Participant Attendance
OpenSynergic/leconfe pull request #335
Opened 2024-08-09 02:19 UTC by SalimQS

Pull request ini memuat 2 fitur di dalamnya, yaitu:
- Conference Agenda: #310 
- Participant Attendance: #324

2024-08-10 00:37 UTC, rahmanramsi commented
![CleanShot 2024-08-10 at 08 36 04](https://github.com/user-attachments/assets/e20960db-e683-40eb-a20b-fdfd2caea253)

2024-08-10 01:09 UTC, SalimQS commented
> ![CleanShot 2024-08-10 at 08 36 04](https://private-user-images.githubusercontent.com/48276043/356777816-e20960db-e683-40eb-a20b-fdfd2caea253.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNTIzOTAsIm5iZiI6MTcyMzI1MjA5MCwicGF0aCI6Ii80ODI3NjA0My8zNTY3Nzc4MTYtZTIwOTYwZGItZTY4My00MGViLWEyMGItZmRmZDJjYWVhMjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDAxMDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNGM0YzYxNTNiYjdlNzk5M2JjZmYzYmUyYzI4YTg4ZDdjODc4ZjYzZmM5MTI2MGNkNTI4OTkyMmExMTVhOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PWKsvclGSLRT6mz4Xb2kGIOM2HaXyzs4jnIozxf56xM)

![image](https://github.com/user-attachments/assets/8cd8f1e8-88d7-421b-aceb-73eaef7bad6e)

2024-08-10 02:03 UTC, rahmanramsi requested changes

2024-08-10 02:03 UTC, rahmanramsi commented on app/Frontend/ScheduledConference/Pages/Agenda.php
> +    public function attend($data_id, $data_type): void
variable nya ubah jadi $id & $type aja, kda usah pakai `data`

2024-08-10 02:03 UTC, rahmanramsi commented on app/Frontend/ScheduledConference/Pages/Agenda.php
> +        // belum login
comment yang seperti ini sebaiknya dihapus saja, biasakan membuat code yang bisa dipahami tanpa perlu ada comment.

Jika memang codenya rumit, baru dijelaskan dengan rinci code tersebut melalui comment

2024-08-10 02:03 UTC, rahmanramsi commented on app/Models/Registration.php
> +    }
Seharusnya fungsi ini tidak memperbolahkan variable yg dikirim null, jika yg dikirim null maka seharusnya error.
Jadi si pemakai fungsi ini harus terlebih dahulu memastikan bahwa variable yang dikirim itu ada

2024-08-10 02:03 UTC, rahmanramsi commented on app/Models/Session.php
> +                Carbon::parse($this->time_end)->format(Setting::get('format_time'))
Seharusnya kolom yang isinya tanggal, otomatis di cast sebagai format tanggal. 
Jadi kita tidak perlu melakukan `Carbon::parse`

Pelajari cast disini https://laravel.com/docs/11.x/eloquent-mutators#attribute-casting

2024-08-10 02:03 UTC, rahmanramsi commented on app/Models/Session.php
> +        if($this->timeline()->first()->isRequiresAttendance()) {
Untuk query relationship sebisa mungkin jangan dipanggil menggunakan function, namun melalui atribute, agar eager loading berguna

2024-08-10 02:03 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Livewire/Registration/RegistrationTypes.php
Nama komponen harus menggambarkan konteks sesuai fungsi komponen tersebut. Semisal component adalah sebuah form, Maka diakhir namanya ditambahkan `Form`. 
Contoh bisa dilihat dari component" yang sudah ada

2024-08-10 02:03 UTC, rahmanramsi commented on database/migrations/2024_04_15_065715_create_timelines_table.php
> +            $table->boolean('requires_attendance')->default(false);
ini konteksnya jamak atau tunggal ?

2024-08-10 02:03 UTC, rahmanramsi commented on database/migrations/2024_08_02_085328_create_agendas.php
nama file disesuaikan dengan isinya

2024-08-10 02:03 UTC, rahmanramsi commented on resources/views/frontend/scheduledConference/pages/agenda.blade.php
> +@use('Illuminate\Support\Str')
tidak perlu dipakai, karena `Illuminate\Support\Str` sudah dialiaskan menjadi `Str`.

2024-08-10 02:03 UTC, rahmanramsi commented on resources/views/frontend/scheduledConference/pages/agenda.blade.php
> +                                    {{ Carbon::parse($timeline->date)->format(Setting::get('format_date')) }}
kolom date sudah di cast menjadi date object, jadi tidak perlu diparse lagi.
![CleanShot 2024-08-10 at 10 01 16](https://github.com/user-attachments/assets/600f61be-25e4-492a-9841-c19e6a30fd2b)

2024-08-10 02:26 UTC, SalimQS commented on database/migrations/2024_04_15_065715_create_timelines_table.php
> +            $table->boolean('requires_attendance')->default(false);
tunggal ka, nama column sudah diganti jadi `require_attendance`

2024-08-10 03:54 UTC, SalimQS commented
bug pengecekan waktu pada timeline dan session, dimana session menggunakan tanggal timeline, dan timeline menggunakan waktu dari session

2024-08-13 00:07 UTC, rahmanramsi approved these changes

2024-08-13 00:08 UTC, rahmanramsi commented
Tolong di resolve conflict nya, sama tambahkan translasinya

2024-08-13 01:25 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Livewire/Payment/PaymentManualTable.php
Beberapa label belum di translate

2024-08-13 01:25 UTC, rahmanramsi commented on app/Panel/ScheduledConference/Livewire/Registration/RegistrationSetting.php
> +                            ->label('Attendance Feature')
translate

2024-08-13 01:26 UTC, rahmanramsi requested changes
Pastikan bahwa semua string support translation

2024-08-13 02:37 UTC, SalimQS commented on app/Frontend/ScheduledConference/Pages/ParticipantRegister.php
> +        return redirect(request()->header(__('general.referer')));
ini nama header, bukan teks yang akan ditampilkan untuk user, ini tidak perlu di translasikan

2024-08-13 02:37 UTC, SalimQS commented on app/Frontend/ScheduledConference/Pages/ParticipantRegister.php
> +            __('gemeral.participant_registration'),
ini pengejaannya apakah sudah benar, tolong dicek lagi

2024-08-13 02:37 UTC, SalimQS commented on app/Frontend/ScheduledConference/Pages/Timelines.php
> +            __('general.timeline'),
ikuti konteks penulisan sebelumnya, apakah konteks nya hanya satu atau jamak (banyak), disini berarti seharusnya `timelines`

2024-08-13 02:52 UTC, rahmanramsi commented
Menu registration setting hilang
![CleanShot 2024-08-13 at 10 51 38](https://github.com/user-attachments/assets/fe22914d-f876-4fdf-9601-b35c9989f7cb)

2024-08-13 03:00 UTC, rahmanramsi commented
Secara default, policy method tidak mereturn apa", agar bisa dihook ketika ada yg ingin mengextend fungsionalitas. Jadi harusnya tidak mereturn false dibagian akhirnya.
![CleanShot 2024-08-13 at 10 52 23](https://github.com/user-attachments/assets/57f9775e-659b-441c-90d6-9f03c066a3b0)

Contoh di policy lain : 
![CleanShot 2024-08-13 at 11 00 00](https://github.com/user-attachments/assets/9ab297de-80e0-403d-8910-26322410e130)

2024-08-13 03:01 UTC, rahmanramsi commented
![CleanShot 2024-08-13 at 11 00 48](https://github.com/user-attachments/assets/89230216-af9e-4fea-8dcf-da3857a8ef94)

2024-08-13 03:08 UTC, rahmanramsi commented
![CleanShot 2024-08-13 at 11 08 22](https://github.com/user-attachments/assets/05499fd4-508d-4049-a73b-d263c77e40e9)

2024-08-13 03:29 UTC, rahmanramsi commented
![CleanShot 2024-08-13 at 11 27 58](https://github.com/user-attachments/assets/4580a7cd-d907-4da8-9df2-97fc7fb6f7b2)
Dan juga gunakan enable javascript date input nya https://filamentphp.com/docs/3.x/forms/fields/date-time-picker#enabling-the-javascript-date-picker

2024-08-13 09:52 UTC, rahmanramsi approved these changes

2024-08-13 09:52 UTC, merged