342 author submission
OpenSynergic/leconfe pull request #347
Opened 2024-08-15 02:17 UTC by SalimQS

prevent author to continue the submission process before registering as participant (author level)

2024-08-15 02:17 UTC, SalimQS commented
need to translate

2024-08-15 03:29 UTC, SalimQS commented on resources/views/panel/scheduledConference/livewire/submissions/payment.blade.php
> +                            <a href="{{ route('livewirePageGroup.scheduledConference.pages.participant-registration') }}" class="text-sm text-blue-500 hover:text-blue-700 hover:underline">{{ __('gene
ini html characternya ditinggal aja, contoh `{{ __('general.registration_page') }} &rsaquo;`

2024-08-15 03:29 UTC, SalimQS commented on resources/views/panel/scheduledConference/livewire/submissions/payment.blade.php
> +                                            {{ __('general.unassigned') }}
ini seharusnya unpaid

2024-08-15 07:47 UTC, rahmanramsi commented
Awal submit sudah langsung di minta pembayaran ?
![CleanShot 2024-08-15 at 15 47 12](https://github.com/user-attachments/assets/58725e1c-bf8e-4203-b371-1b95eeb78627)

2024-08-15 07:48 UTC, rahmanramsi commented
Disini statusnya queued
![CleanShot 2024-08-15 at 15 48 05](https://github.com/user-attachments/assets/c1bb3e6d-f91d-4c78-8fc7-f2dc89a443c4)


Tetapi ketika didetail submission statusnya waiting payment
![CleanShot 2024-08-15 at 15 48 37](https://github.com/user-attachments/assets/4736d4bb-02a6-4e2f-9a8c-aa3b9360c373)

2024-08-16 00:06 UTC, rahmanramsi commented on helpers/helpers.php
> +}
kenapa penamaan nya fixedMoney?

2024-08-16 00:07 UTC, rahmanramsi commented on helpers/helpers.php
> +    }
kenapa penamaannya fixedCurrency?

2024-08-16 03:00 UTC, SalimQS commented on helpers/helpers.php
> +}
karena function helper ini menggantikan dan memperbaiki kekurangan  function helper `money` ka

2024-08-16 03:06 UTC, SalimQS commented on helpers/helpers.php
> +}
apakah harus diganti ka

2024-08-19 02:00 UTC, rahmanramsi commented
Status payment seharusnya masuk kedalam `SubmissionStatus`, dan `SubmissionStage` bukan hal yang terpisah. Saat ini implementasinya terpisah

2024-08-19 02:06 UTC, rahmanramsi commented
![CleanShot 2024-08-19 at 10 04 10](https://github.com/user-attachments/assets/2a69a535-000d-401e-ba71-542428056753)

Untuk pesannya bisa diubah menjadi, Payment for submission currently not open, please see `Timelines` for more details.

2024-08-19 02:08 UTC, rahmanramsi commented
![CleanShot 2024-08-19 at 10 06 49](https://github.com/user-attachments/assets/955e7207-026e-4483-bc0c-f8b8a9de7204)
Tidak ada aksi yang bisa dilakukan oleh author untuk melanjutkan ke proses pembayaran. Yang diperlukan bukan cuman instruksi, tapi `CTA` yang bisa dilakukan oleh user

2024-08-19 02:12 UTC, rahmanramsi commented
Pesan yang diberikan seharusnya berbeda antara yg melakukan submit, dan yg melakukan review.
![CleanShot 2024-08-19 at 10 11 34](https://github.com/user-attachments/assets/cfcbfa89-94b9-440f-9688-884002a3ad9a)

2024-08-24 00:20 UTC, rahmanramsi commented
## Modal assign participant tertumpuk dengan header
![CleanShot 2024-08-24 at 08 19 03](https://github.com/user-attachments/assets/4bba2d02-4720-4909-b1f9-a5490bbb166e)

2024-08-24 00:24 UTC, rahmanramsi commented
Kenapa banyak menggunakan warna blue ?
Padahal warna blue bukan warna primary yang digunakan oleh aplikasi.
![CleanShot 2024-08-24 at 08 22 55](https://github.com/user-attachments/assets/28210f5e-f9ae-42d8-b4b8-5506466242e9)

2024-08-24 00:35 UTC, rahmanramsi commented
Tambahkan tombol untuk memberitahu user bahwa section tersebut bisa diklik
![CleanShot 2024-08-24 at 08 33 52](https://github.com/user-attachments/assets/74f65472-b5d9-4d61-8fc7-ed0718e5a0ca)


Modal conflict dengan header
![CleanShot 2024-08-24 at 08 33 06](https://github.com/user-attachments/assets/dea1541a-0e74-483b-b53c-a15687ab571b)

2024-08-24 00:35 UTC, rahmanramsi commented
Tambahkan tombol untuk memberitahu user bahwa section tersebut bisa diklik
![CleanShot 2024-08-24 at 08 35 24](https://github.com/user-attachments/assets/7ab9d3e0-f0b8-47d2-8699-f2b9dd400a61)

2024-08-24 00:42 UTC, rahmanramsi commented
Registration proses belum dimulai padahal sudah dimulai
![CleanShot 2024-08-24 at 08 40 58](https://github.com/user-attachments/assets/734660ca-4ff8-4833-b191-00ba5c288daa)

![CleanShot 2024-08-24 at 08 41 34](https://github.com/user-attachments/assets/9a154a96-e38b-4d85-87f4-8a518cc55a93)

Cara reproduksinya : 
1. Submit paper menggunakan user author. 
2. Kemudian accept menggunakan user conference editor

2024-08-24 00:45 UTC, rahmanramsi commented
Disaat melakukan accept abstract menggunakan user conference editor, user tersebut ditambahkan lagi ke participant, padahal user tersebut sudah terdaftar kedalam participant.
![CleanShot 2024-08-24 at 08 44 43](https://github.com/user-attachments/assets/4c2e4196-0b74-4cc7-ae33-c2a054070827)

2024-08-24 01:09 UTC, SalimQS commented
![image](https://github.com/user-attachments/assets/a9e528ef-3d60-40a8-9fad-3621c15e6dbd)
author/non editor dapat melihat action yang seharusnya hanya dapat diakses editor

2024-08-24 02:24 UTC, SalimQS commented
> Disaat melakukan accept abstract menggunakan user conference editor, user tersebut ditambahkan lagi ke participant, padahal user tersebut sudah terdaftar kedalam participant. ![CleanShot 2024-08-24 at 08 44 43](https://private-user-images.githubusercontent.com/48276043/361089817-4c2e4196-0b74-4cc7-ae33-c2a054070827.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NjY0NDcsIm5iZiI6MTcyNDQ2NjE0NywicGF0aCI6Ii80ODI3NjA0My8zNjEwODk4MTctNGMyZTQxOTYtMGI3NC00Y2M3LWFlMzMtYzJhMDU0MDcwODI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDAyMjIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmODliMWJkZDJjZDEzZjVkNjMzYTg3Y2MxMTAwOTEzNDQ2N2I5YTJiNWMwYTBkZTBmMjExODI5NjRkYzJiM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5EPkARZx_91kLvUhOVi3gMEvXVXCyVgZYEYLZ-Ak-Pw)

ka, bisa tolong tambahkan cara reproduce bugnya ka

2024-08-24 07:23 UTC, rahmanramsi commented
![CleanShot 2024-08-24 at 15 22 10](https://github.com/user-attachments/assets/8fce1b6b-7428-4577-80b9-482aaf4725ea)

2024-08-24 07:28 UTC, rahmanramsi commented
Disable saja tampilan `sticky` di sidebar kanan untuk fix notification modal tertimpa
![CleanShot 2024-08-24 at 15 27 27](https://github.com/user-attachments/assets/be8f8afa-f2f8-482a-b058-2f915dde907d)

2024-08-28 08:08 UTC, rahmanramsi requested changes

2024-08-28 08:08 UTC, rahmanramsi commented on lang/ar/general.php
> +    'go_to_submission_page' => 'انتقل إلى <a href=":url" class="text-blue-500">صفحة الاستلامات</a> للتحقق من حالة تقديمك.',
kenapa warna brand primary diganti jadi blue ?

2024-08-28 08:08 UTC, rahmanramsi commented on resources/frontend/css/frontend.css
> +    }
ini style buat apa ?

2024-08-28 08:08 UTC, rahmanramsi commented on resources/panel/css/panel.css
> +
ini style buat apa ?

2024-08-28 08:08 UTC, rahmanramsi commented on app/Utils/UpgradeSchemas/UpgradeBeta4.php
> +		});
metadata default seharusnya di taro di `getAllDefaultMeta` didalam modelnya, jangan diset kedatabase.

2024-08-28 08:08 UTC, rahmanramsi commented on database/migrations/2024_08_28_063642_add_column_beta_4.php
> +        }
script ini harusnya di dalam proses upgrade. bukan di migration, karena hanya diperlukan saat upgrade

2024-08-29 00:29 UTC, SalimQS commented on resources/frontend/css/frontend.css
> +    }
untuk memperbaiki tampilan style policy dll yang berbeda dari apa yang di input user ka

2024-08-29 00:29 UTC, SalimQS commented on resources/frontend/css/frontend.css
> +    }
untuk memperbaiki tampilan style policy dll yang berbeda dari apa yang di input user ka

2024-08-29 00:48 UTC, SalimQS commented on lang/ar/general.php
> +    'go_to_submission_page' => 'انتقل إلى <a href=":url" class="text-blue-500">صفحة الاستلامات</a> للتحقق من حالة تقديمك.',
![image](https://github.com/user-attachments/assets/8e8e70e1-91b6-496c-a318-ff7ded9e3923)

di commitan terakhir warna masih tetap `text-primary` ka, 
diubah dari yang tadinya 700, karena warnanya gelap, hampir ngeblend sama warna hitam

2024-08-29 00:50 UTC, SalimQS commented on resources/panel/css/panel.css
> +
untuk memperbaiki tampilan style policy dll yang berbeda dari apa yang di input user ka

2024-08-29 00:55 UTC, SalimQS commented on app/Utils/UpgradeSchemas/UpgradeBeta4.php
> +		});
agak sedikit berlebihan menurut ulun ka misal dua metadata ini dimasukkan kedalam function `getAllDefaultMeta`..

2024-08-29 08:16 UTC, rahmanramsi approved these changes

2024-08-29 08:16 UTC, merged